### ISSUE TITLE
Current state?

### ISSUE THREAD

**Issue by tino** [benoitc/gaffer#44]
I installed 0.5.2, and immediately noticed that there are some discrepancies between docs and code. Also, on my local machine stuff works fine, but on my server I can't do anything because authentication is suddenly required (while ``--require-keys`` is not set). And creating an admin and using the key does not work, so I can't do anything on that server.

What is the status of master, and which version is usable?

**Comment by benoitc** [comment]
works on it restarted. Keep it posted.
