### ISSUE TITLE
No output from Procfile processes when run with gaffer

### ISSUE THREAD

**Issue by djrobstep** [benoitc/gaffer#45]
For instance:

Procfile:

```
dummy: python -u -m SimpleHTTPServer
```

Then:

gaffer dev:start

```
17:35:53 x.dummy | start x.dummy
17:35:53 x.dummy | spawn process with pid 1
```

Where I would expect to see:
```
Serving HTTP on 0.0.0.0 port 8000 ...
```
with the output.

My OS is Ubuntu 13.10 if that's relevant.

**Comment by benoitc** [comment]
you need to redirect the stdout too to see it.
