### ISSUE TITLE
Loading a Procfile without launching it

### ISSUE THREAD

**Issue by steelstyle** [benoitc/gaffer#56]
Give the ability to start just some or no process when loading a Procfile.
I started a simple solution here : https://github.com/steelstyle/gaffer/tree/nostart_jobs

It's helpful when some process are mean to be one-off process.

**Comment by benoitc** [comment]
Good idea :) Can you open a PR for it? I also commented the code.

**Comment by steelstyle** [comment]
Yes of course, but I keep hesitating between ;
* A simple paramater as `--no-start` assuming the following call should start the correct jobs (which can be tedious and subject to error)
* Or something like http://ddollar.github.io/foreman/#EXAMPLES where you have : 

>Start all processes except the one named worker:
>$ foreman start -c all=1,worker=0

**Comment by benoitc** [comment]
fixed in master.
